# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0a8d032fd696fb6204ac5765e1456a6ee235b36bd9256f9ff79b773dd8f181ef627484d47c2b396f4da6398f21a1f0f6b9f07ec24522dd8acfd7c35b341cc8b

test:
  secret_key_base: 40d465c209581ce29a6420b23d50b209c0cdb2ea7f28c175760a1dae22db220bd865072bdb29291851be58b60d3a968692239476d3194d676923720acefd84db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
